server:
  port: 80
  servlet:
    context-path: /mybatisplus
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.153.197.70:3306/currency?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: dev
    password: Dev@baowugroup.com
    hikari:
      #最小连接
      minimum-idle: 5
      #最大连接
      maximum-pool-size: 15
      #自动提交
      auto-commit: true
      #最大空闲时间
      idle-timeout: 30000
      #连接池名称
      pool-name: DatebookHikariCP
      #最大生命周期
      max-lifetime: 900000
      #连接超时时间
      connection-timeout: 15000
      #心跳检测
      connection-test-query: select 1
  redis:
    database: 0
    host: 118.126.104.111
    port: 6379
    password: zzmAdmin
    timeout: 3000
    jedis:
      pool:
        max-active: 2000
        max-wait: 1000
        min-idle: 50

  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  #xml路径
  mapper-locations: classpath:mapping/*Mapper.xml
  #model路径
  typeAliasesPackage: com.runrunfast.currency.entity

# Logger Config
logging:
  level:
    #日志级别从低到高分为：TRACE < DEBUG < INFO < WARN < ERROR < FATAL
    com.runrunfast.currency: DEBUG
#配置swagger2
swagger2:
  VERSION: v1.0
  SWAGGER_SCAN_BASE_PACKAGE: com.runrunfast.currency
  TITLE: mybatis-puls
  DESCRIPTION: API文档

